name: [Auto] Deploy Dev

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i
        
      - name: Build Angular App
        run: npm run build
        
      - name: Create Release Asset
        run: |
          cd dist/angular-project
          zip -r theme.zip .
          mv theme.zip ../../theme.zip
          
      - name: Configure Deployment
        uses: tanyagray/create-json-string@1.1.0
        id: deployment_config
        with:
          slot: "UI"
          alias: "theme_dev"
          artifact: ${{ steps.upload_release_asset.outputs.browser_download_url }}
          
      - name: Deploy for Soul Files
        uses: avakar/create-deployment@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_merge: false
          production_environment: false
          environment: dev
          payload: ${{ steps.deployment_config.outputs.json_string }}
