# requires a tag, or a release id
# grabs the asset
# publishes it

name: Deploy Staging [Auto]

on:
  release:
    types: [published]

jobs:

  deploy-staging:

    runs-on: ubuntu-latest

    steps:

      - uses: cardinalby/git-get-release-action@v1.1
        id: get_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          prerelease: true

      - name: Configure Deployment
        uses: tanyagray/create-json-string@1.1.0
        id: deployment_config
        with:
          slot: UI
          alias: theme_prerelease
          version: v${{ steps.get_release.outputs.tag_name }}
          asset_url: ${{ steps.get_release.outputs.assets_url }}/theme.zip

      - name: Deploy to Staging
        uses: avakar/create-deployment@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_merge: false
          production_environment: false
          required_contexts: ''
          environment: staging
          payload: ${{ steps.deployment_config.outputs.json_string }}
