# requires a tag, or a release id
# grabs the asset
# publishes it

name: Deploy Prod [Auto]

on:
  release:
    types: [released]

jobs:

  deploy-prod:

    runs-on: ubuntu-latest

    steps:

      - name: Get Release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commitSha: ${{ github.sha }}

      - name: Configure Deployment
        uses: tanyagray/create-json-string@1.1.0
        id: deployment_config
        with:
          slot: UI
          alias: theme_stable
          version: v${{ steps.get_release.outputs.tag_name }}
          asset_url: ${{ steps.get_release.outputs.assets_url }}/theme.zip

      - name: Deploy to Prod
        uses: avakar/create-deployment@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_merge: false
          production_environment: true
          required_contexts: ''
          environment: prod
          payload: ${{ steps.deployment_config.outputs.json_string }}
