# requires a tag, or a release id
# grabs the asset
# publishes it

name: Deploy Staging [Auto]

on:
  release:
    types: [prereleased]

jobs:

  deploy-staging:

    runs-on: ubuntu-latest

    steps:

      - uses: cardinalby/git-get-release-action@v1.1
        id: get_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}

      - name: Validate Deployment
        id: validate
        if: ${{ steps.get_release.outputs.prerelease == 'false' }}
        run: |
          echo "Release state is `prerelease: false`"
          echo "Only a prerelease can be deployed to the staging environment."
          exit 1

      - name: Configure Deployment
        uses: tanyagray/create-json-string@1.1.0
        id: deployment_config
        with:
          slot: UI
          alias: theme_dev
          version: v${{ steps.semantic.outputs.new_release_version }}
          asset_url: ${{ steps.upload_release_asset.outputs.url }}

      - name: Deploy to Staging
        uses: avakar/create-deployment@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_merge: false
          production_environment: false
          required_contexts: ''
          environment: dev
          payload: ${{ steps.deployment_config.outputs.json_string }}
