name: Auto | Release Dev

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Bump Version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Release
        id: validate
        if: ${{ steps.semantic.outputs.new_release_published == 'false' }}
        run: |
          echo "Nothing to release: There are no releasable commits."
          echo "Ensure your recent changes include a fix, feature, or breaking change."
          exit 1

      - name: Build Angular App
        run: npm run build

      - name: Create Release Asset
        run: |
          cd dist/angular-project
          zip -r theme.zip .
          mv theme.zip ../../theme.zip

      - name: Update Dev Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: Theme v${{ steps.semantic.outputs.new_release_version }}-dev
          body: ${{ steps.semantic.outputs.new_release_notes }}
          tag: dev
          files: theme.zip
          draft: false
          prerelease: true

      - name: Update Dev Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
