name: Release Dev [Auto]

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Bump Version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Release
        id: validate
        if: ${{ steps.semantic.outputs.new_release_published == 'false' }}
        run: |
          echo "Nothing to release: There are no releasable commits."
          echo "Ensure your recent changes include a fix, feature, or breaking change."
          exit 1

      - name: Build Angular App
        run: npm run build

      - name: Create Release Asset
        run: |
          cd dist/angular-project
          zip -r theme.zip .
          mv theme.zip ../../theme.zip

      - name: Delete Existing Drafts
        uses: hugo19941994/delete-draft-releases@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.semantic.outputs.new_release_version }}
          release_name: Theme v${{ steps.semantic.outputs.new_release_version }}
          body: ${{ steps.semantic.outputs.new_release_notes }}
          draft: true
          prerelease: true
